# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9cc61476fa179b67e62f0c8faa0eb9f0ed4ffed0f0988217bf618606418405467b909023b7133c772348b1a1c8be954a7da5e01ddf248c029f9a01906f8733ab

test:
  secret_key_base: 76fc601b52e164d4050b4e32f0e19af98df1bc70efb0e1c084b1b8a1e28378b777cd61b00c311e09a829de91b56d777bd32d0638ec6bf1eb8f22f8cd7651d9c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
